-- Create tables
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    link TEXT,
    member_id BIGINT NOT NULL REFERENCES members(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    fulfilled BOOLEAN DEFAULT false,
    fulfilled_at TIMESTAMPTZ,
    fulfilled_by BIGINT REFERENCES members(id)
);

-- Pre-seed members
INSERT INTO members (name) VALUES ('Ziwen'), ('Yirui');

-- Travel destinations
CREATE TABLE travels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination TEXT NOT NULL,
    link TEXT,
    note TEXT,
    member_id BIGINT NOT NULL REFERENCES members(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    fulfilled BOOLEAN DEFAULT false,
    fulfilled_at TIMESTAMPTZ
);

-- Anniversary restaurants
CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    link TEXT,
    note TEXT,
    member_id BIGINT NOT NULL REFERENCES members(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    visited BOOLEAN DEFAULT false,
    visited_at DATE,
    review TEXT
);

-- Enable Row Level Security
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishes ENABLE ROW LEVEL SECURITY;

-- Allow public access (family app, no auth needed)
CREATE POLICY "Allow all on members" ON members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on wishes" ON wishes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE travels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all on travels" ON travels FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE restaurants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all on restaurants" ON restaurants FOR ALL USING (true) WITH CHECK (true);
